FROM maven:3.9.3-amazoncorretto-11 AS build

WORKDIR /app

COPY pom.xml .
COPY src/ ./src/

RUN mvn clean package

FROM tomcat:9

RUN rm -rf /usr/local/tomcat/webapps/*

COPY --from=build /app/target/*.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080

CMD ["catalina.sh", "run"]
